services:
  - type: web
    name: cv-platform
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd cv_platform && gunicorn cv_platform.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: "cv_platform"
      - key: COHERE_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true

